sudo: required
dist: trusty
language: python
python:
  - "3.6"
env:
  - CI_TEST=true

before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
  - sudo apt-get install nodejs
install:
  - pip install -r requirements.txt
  - npm install
before_script:
  - ./node_modules/.bin/webpack
  - python manage.py runserver &
  - chmod +x wait-for-it.sh
  - ./wait-for-it.sh -h localhost -p 8000 -t 10
script:
- pytest test/